module.exports = [
  { id: 'SP1', name: 'Chicken & Sweet Corn Soup', price: 40 },
  { id: 'SP2', name: 'Hot & Sour Soup', price: 40 },
  { id: 'S1', name: 'Beef Spring Rolls (3 pcs)', price: 30 },
  { id: 'S2', name: 'Vegetable Spring Rolls (3 pcs)', price: 25 },
  { id: 'S3', name: 'Beef Samosa (5 pcs)', price: 30 },
  { id: 'S4', name: 'Fish Samosa (5 pcs)', price: 30 },
  { id: 'S5', name: 'Fried Chicken Pieces (6 pcs)', price: 65 },
  { id: 'S6', name: 'Special Chicken Wings', price: 65 },
  { id: 'S7', name: 'Golden Fried Prawns', price: 90 },
  { id: 'S8', name: 'Fried Squid in Spicy Salt', price: 85 },
  { id: 'B1', name: 'Shredded Beef with Green Pepper & Onion', price: 110 },
  { id: 'B2', name: 'Beef in Sichuan Sauce', price: 110 },
  { id: 'B3', name: 'Sliced Beef in Curry Sauce', price: 110 },
  { id: 'B4', name: 'Beef in Oyster Sauce', price: 110 },
  { id: 'B5', name: 'Crispy Chilli Beef', price: 85 },
  { id: 'B6', name: 'Mongolian Shallot Lamb', price: 115 },
  { id: 'B7', name: 'Lamb Chops', price: 85 },
  { id: 'P1', name: 'Sweet & Sour Pork', price: 90 },
  { id: 'P2', name: 'Pork Sichuan Style', price: 90 },
  { id: 'P3', name: 'Pork in Chilli Sauce', price: 90 },
  { id: 'P4', name: 'Pork in Oyster Sauce', price: 90 },
  { id: 'P5', name: 'Fried Pork Ribs', price: 75 },
  { id: 'K1', name: 'Sweet & Sour Chicken', price: 100 },
  { id: 'K2', name: 'Chicken Sichuan Sauce', price: 100 },
  { id: 'K3', name: 'Chicken in Curry Sauce', price: 100 },
  { id: 'K4', name: 'Chicken in Oyster Sauce', price: 100 },
  { id: 'Q1', name: 'Squid in Luban Chilli Sauce', price: 120 },
  { id: 'Q2', name: 'Squid in Sichuan Sauce', price: 120 },
  { id: 'Q3', name: 'Squid in Garlic Sauce', price: 120 },
  { id: 'F1', name: 'Fish Fillet in Chilli Sauce', price: 115 },
  { id: 'F2', name: 'Fish Fillet in Vegetable Sauce', price: 115 },
  { id: 'F3', name: 'Fish Fillet in Sichuan Sauce', price: 115 },
  { id: 'F4', name: 'Sweet & Sour Fish Fillet', price: 115 },
  { id: 'PR1', name: 'Prawns in Chilli Sauce', price: 155 },
  { id: 'PR2', name: 'Prawns in Curry Sauce', price: 155 },
  { id: 'PR3', name: 'Prawns in Sichuan Sauce', price: 155 },
  { id: 'SF1', name: 'Special Seafood in Sichuan Sauce', price: 170 },
  { id: 'R1', name: 'Steamed Rice', price: 29 },
  { id: 'R2', name: 'Special Jollof Rice', price: 50 },
  { id: 'R3', name: 'Combo Fried Rice', price: 50 },
  { id: 'R4', name: 'Shrimp Fried Rice', price: 50 },
  { id: 'R5', name: 'Egg Fried Rice', price: 40 },
  { id: 'R6', name: 'Beef Fried Rice', price: 45 },
  { id: 'R7', name: 'Chicken Fried Rice', price: 45 },
  { id: 'R8', name: 'Seafood Fried Rice', price: 85 },
  { id: 'R9', name: 'Pork Fried Rice', price: 45 },
  { id: 'N1', name: 'Vegetable Noodles', price: 45 },
  { id: 'N2', name: 'Special Noodles', price: 80 },
  { id: 'N4', name: 'Singapore Noodles', price: 80 },
  { id: 'N5', name: 'Seafood Noodles', price: 100 },
  { id: 'N6', name: 'Chicken Noodles', price: 60 },
  { id: 'D1', name: 'Steamed Pork Dumpling', price: 30 },
  { id: 'D2', name: 'Fried Pork Dumpling', price: 30 },
  { id: 'D3', name: 'Steamed Beef Dumpling', price: 30 },
  { id: 'D4', name: 'Fried Beef Dumpling', price: 30 },
  { id: 'V1', name: 'Mixed Vegetable Sauce', price: 40 },
  { id: 'DR1', name: 'Coca-Cola 300ml', price: 15 },
  { id: 'DR2', name: 'Fanta 300ml', price: 15 },
  { id: 'DR3', name: 'Sprite 300ml', price: 15 },
  { id: 'DR4', name: 'Water 300ml', price: 5 }
];
