import {
  createIcons,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BadgePercent,
  BookOpen,
  Bot,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Check,
  CheckCircle,
  ChefHat,
  CircleAlert,
  CircleUserRound,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  GraduationCap,
  HeartHandshake,
  HelpCircle,
  Home,
  Image,
  Info,
  LayoutDashboard,
  Leaf,
  Loader,
  LogIn,
  LogOut,
  Mail,
  MailX,
  Map,
  MapPin,
  Menu,
  MessageSquare,
  Navigation,
  Package,
  PartyPopper,
  Pencil,
  Phone,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  RotateCcw,
  Save,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  Sparkles,
  Trash2,
  Truck,
  UploadCloud,
  User,
  UserCheck,
  Utensils,
  UtensilsCrossed,
  X
} from 'lucide';

const icons = {
  'alert-circle': AlertCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-percent': BadgePercent,
  'book-open': BookOpen,
  'bot': Bot,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'camera': Camera,
  'check': Check,
  'check-circle': CheckCircle,
  'chef-hat': ChefHat,
  'circle-alert': CircleAlert,
  'circle-user-round': CircleUserRound,
  'clock': Clock,
  'copy': Copy,
  'download': Download,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'graduation-cap': GraduationCap,
  'heart-handshake': HeartHandshake,
  'help-circle': HelpCircle,
  'home': Home,
  'image': Image,
  'info': Info,
  'instagram': Camera,
  'layout-dashboard': LayoutDashboard,
  'leaf': Leaf,
  'linkedin': Share2,
  'loader': Loader,
  'log-in': LogIn,
  'log-out': LogOut,
  'mail': Mail,
  'mail-x': MailX,
  'map': Map,
  'map-pin': MapPin,
  'menu': Menu,
  'message-square': MessageSquare,
  'navigation': Navigation,
  'package': Package,
  'party-popper': PartyPopper,
  'pencil': Pencil,
  'phone': Phone,
  'plus': Plus,
  'printer': Printer,
  'qr-code': QrCode,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'save': Save,
  'settings': Settings,
  'share-2': Share2,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'sparkles': Sparkles,
  'trash-2': Trash2,
  'truck': Truck,
  'twitter': X,
  'upload-cloud': UploadCloud,
  'user': User,
  'user-check': UserCheck,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'x': X
};

const normalizedIcons = Object.keys(icons).reduce((acc, key) => {
  // Lucide v1 resolves icon names via PascalCase internally.
  const pascalKey = key
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  acc[pascalKey] = icons[key];
  return acc;
}, {});

window.lucide = {
  createIcons: (attrs) => createIcons({ icons: normalizedIcons, attrs }),
  icons
};
